name: "Get semver part"
description: "Maps a Pull Request's labels to semver parts"
branding:
  icon: 'clock'
  color: 'orange'
inputs:
  githubToken:
    description: 'Your GitHub token'
    required: true
  major:
    description: 'Comma-separated map of labels for MAJOR bump'
    required: false
    default: ''
  minor:
    description: 'Comma-separated map of labels for MINOR bump'
    required: false
    default: ''
  patch:
    description: 'Comma-separated map of labels for PATCH bump'
    required: false
    default: ''
  defaultPart:
    description: 'Default SemVer part if none of the labels apply.'
    required: false
    default: 'null'
outputs:
  part:
    description: 'the part to increment'
runs:
  using: 'docker'
  image: 'Dockerfile'
